### ISSUE TITLE
Add Once[]

### ISSUE THREAD

**Issue by ianhorswill** [ianhorswill/TED#19]

**Comment by SamuelHill** [comment]
Ideally this would be some generic `DoXNumTimes[]` where not only could you do `Once` but also 5 or any other number of limited bindings. Alternative to `Count` where I only need X number to be true - the count value is irrelevant.

 Also replaces !! or NonZero:
```cs
public static Goal Goals(params Goal[] goals) =>
    goals.Length == 0 ? null : goals.Aggregate((current, goal) => current & goal);
public static Goal NonZero(Goal goal) => !!goal;
public static Goal NonZero(params Goal[] goals) => NonZero(Goals(goals));
```
