### ISSUE TITLE
Alternative to ForceDynamic

### ISSUE THREAD

**Issue by SamuelHill** [ianhorswill/TED#28]
Alternative - add ability to mark `Function`s and `PrimitiveTest`s as dynamic, then in preprocessing use this to mark table as dynamic. Currently we assume all `Function`s and `PrimitiveTest`s are static and deterministic.

_Originally posted by @SamuelHill in https://github.com/ianhorswill/TED/issues/25#issuecomment-1555884987_

**Comment by ianhorswill** [comment]
Yes.  I think this is what we want to do.
