### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by SamuelHill** [ianhorswill/TED#7]
- [ ] Missing XML comments for...
     - [ ] AndPrimitive
     - [ ] FunctionCall
     - [ ] Pattern
     - [ ] PrimitivePredicate
     - [ ] TableGoal
     - [ ] TablePredicate
     - [ ] TedFunction
     - [ ] Term
- [ ] Make comments/documentation more standardized (i.e. normalize terminology even in docstrings)
- [ ] Update Tests and TablePredicateViewer comments

**Comment by SamuelHill** [comment]
I can handle taking a base version of the documentation for a given public function/property/etc. and applying the same language to the various multi-typed overloads. Otherwise not sure on what the documentation changes should look like yet.

**Comment by ianhorswill** [comment]
Did you do these already.  My build doesn’t seem to think there are any missing XML docs for public things.
That said, things like AndPrimitive probably aren’t public.  But it does have a comment.

**Comment by SamuelHill** [comment]
![image](https://user-images.githubusercontent.com/5816949/226481859-f43bbc9f-bee0-4461-a338-ce368cfe0e4e.png)

My build is still showing about 300 messages for updating XML - I suppressed these to just show up as messages.

**Comment by ianhorswill** [comment]
Fixed!
