### ISSUE TITLE
Predicate.Accumulates[varX, varY].If(...)

### ISSUE THREAD

**Issue by SamuelHill** [ianhorswill/TED#9]
Add temporary tables (of sorts) to `Predicates` to simplify the following pattern:

```cs
Locations = FromCsv("Locations", "locations.csv", location, position.Key, founded, opening);
NewLocations = Predicate("NewLocations", location, position, founded, opening);
NewLocations.If(FreeLot[position], location == NewLocation["Location name", LocationType], ...);
Locations.Accumulates(NewLocations);
```

Ideally the pattern would allow for statements like:

```cs
Locations = FromCsv("Locations", "locations.csv", location, position.Key, founded, opening);
Locations.Accumulates[location, position, founded, opening].If(FreeLot[position], location == NewLocation["Location name", LocationType], ...);
```
OR (using the same variables specified in the `Predicate`):
```cs
Locations = FromCsv("Locations", "locations.csv", location, position.Key, founded, opening);
Locations.Accumulate.If(FreeLot[position], location == NewLocation["Location name", LocationType], ...);
```

One last want would be for these temporary tables to be accessible as a regular predicate in the case that there is some additional logic to be done on them. Above, `NewLocations` is used for some logic that drives tile generation and as such `Locations.Accumulate` would need to have similar accessibility. However, such cases may be better represented as separate predicates - as they already are - so this may not be needed.

**Comment by ianhorswill** [comment]
Done, but ended up naming it Add rather than Accumulates
